### ISSUE TITLE
(QOL) Joining Clause for List on Raffle Roles "List" command

### ISSUE THREAD

**Issue by FoxBotGames** [Ranzer1255/GrimcoRaffleBot#15]
Line 28 on raffle/commands/manage is appending the text " ," to a list when calling for a list of permitted discord roles to run raffles. Suggestion is to make this text ", " as to resolve issue. (See #bot_test_pvt on the TLOG server for reference)
Not necessary but wanted to point out exact issue location in relation to "Hmm" comment on Discord server.

**Comment by Ranzer1255** [comment]
fixed as of 7ef63829de1cd58626dd4b27250603f81296a3da
